apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebookplatform
  labels:
    app: ebookplatform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebookplatform
  template:
    metadata:
      labels:
        app: ebookplatform
    spec:
      containers:
        - name: ebookplatform
          image: "a0717.azurecr.io/ebookplatform3:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
