name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./manageauthor/pom.xml
          mvn clean package -f ./adminsystem/pom.xml
          mvn clean package -f ./ebookplatform/pom.xml
          mvn clean package -f ./subscriber/pom.xml
          mvn clean package -f ./aisystem/pom.xml

      - name: Docker Build and push for Manageauthor
        uses: docker/build-push-action@v4
        with:
          context: ./manageauthor
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/manageauthor:latest
            ghcr.io/${{ github.repository }}/manageauthor:${{ github.ref_name }}
            
      - name: Docker Build and push for Adminsystem
        uses: docker/build-push-action@v4
        with:
          context: ./adminsystem
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/adminsystem:latest
            ghcr.io/${{ github.repository }}/adminsystem:${{ github.ref_name }}
            
      - name: Docker Build and push for Ebookplatform
        uses: docker/build-push-action@v4
        with:
          context: ./ebookplatform
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ebookplatform:latest
            ghcr.io/${{ github.repository }}/ebookplatform:${{ github.ref_name }}
            
      - name: Docker Build and push for Subscriber
        uses: docker/build-push-action@v4
        with:
          context: ./subscriber
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/subscriber:latest
            ghcr.io/${{ github.repository }}/subscriber:${{ github.ref_name }}
            
      - name: Docker Build and push for Aisystem
        uses: docker/build-push-action@v4
        with:
          context: ./aisystem
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/aisystem:latest
            ghcr.io/${{ github.repository }}/aisystem:${{ github.ref_name }}
            
