import React, { useState } from 'react';
import AppBar from '../components/AppBar';
import Footer from '../components/Footer';

const AISystem = () => {
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [description, setDescription] = useState('');
  const [coverUrl, setCoverUrl] = useState('');
  const [summary, setSummary] = useState('');
  const [price, setPrice] = useState('');
  const [category, setCategory] = useState('');

  const handleCoverGeneration = () => {
    setCoverUrl('https://via.placeholder.com/800x450.png?text=AI+Generated+Cover');
  };

  const handleSummaryCreation = () => {
    setSummary('This is a sample summary generated by AI based on the content.');
  };

  const handlePriceCategoryRecommendation = () => {
    setPrice('$9.99');
    setCategory('Romance');
  };

  return (
    <div className="min-h-screen flex flex-col bg-white font-sans">
      <AppBar />
      <div className="px-10 py-8 flex-1">
        <h1 className="text-3xl font-bold mb-1">AI Features</h1>
        <p className="text-gray-600 mb-6">Enhance your e-books with AI-powered tools</p>

        {/* Cover Generation */}
        <section className="mb-6">
          <h2 className="text-xl font-bold mb-2">Cover Generation</h2>
          <input
            className="w-full border p-3 rounded mb-2"
            placeholder="Enter book title"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />
          <button onClick={handleCoverGeneration} className="bg-blue-600 text-white px-4 py-2 rounded">Generate Cover</button>
        </section>

        {/* Summary Creation */}
        <section className="mb-6">
          <h2 className="text-xl font-bold mb-2">Summary Creation</h2>
          <input
            className="w-full border p-3 rounded mb-2"
            placeholder="Paste book content"
            value={content}
            onChange={(e) => setContent(e.target.value)}
          />
          <button onClick={handleSummaryCreation} className="bg-blue-600 text-white px-4 py-2 rounded">Generate Summary</button>
        </section>

        {/* Price & Category */}
        <section className="mb-6">
          <h2 className="text-xl font-bold mb-2">Price & Category Recommendation</h2>
          <input
            className="w-full border p-3 rounded mb-2"
            placeholder="Enter book description"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
          />
          <button onClick={handlePriceCategoryRecommendation} className="bg-blue-600 text-white px-4 py-2 rounded">Recommend</button>
        </section>

        {/* Preview */}
        <section className="mb-6">
          <h2 className="text-xl font-bold mb-2">Preview</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {/* Book Cover Card */}
            {coverUrl && (
              <div className="border rounded p-4 shadow-md bg-white text-center">
                <h3 className="font-semibold mb-2 text-gray-700">📘 Generated Book Cover</h3>
                <img src={coverUrl} alt="Generated Cover" className="object-cover rounded border w-full h-auto" />
              </div>
            )}

            {/* Summary Card */}
            {summary && (
              <div className="border rounded p-4 shadow-md bg-white">
                <h3 className="font-semibold mb-2 text-gray-700">📝 AI Summary</h3>
                <p className="text-gray-800">{summary}</p>
              </div>
            )}

            {/* Price & Category Card */}
            {(price || category) && (
              <div className="border rounded p-4 shadow-md bg-white">
                <h3 className="font-semibold mb-2 text-gray-700">💰 Price & Category</h3>
                {price && <p className="text-gray-800 mb-2"><strong>Price:</strong> {price}</p>}
                {category && <p className="text-gray-800"><strong>Category:</strong> {category}</p>}
              </div>
            )}
          </div>
        </section>
      </div>
      <Footer />
    </div>
  );
};

export default AISystem;
